[RDT-3] Replace Header
DJ-Chemik/Mercurius pull request #1
Opened 2022-03-01 19:11 UTC by Simon0030

2022-03-01 19:17 UTC, kostekd commented on front/src/components/App/MainPage/MainPage.tsx
> +    <Header >
Nieodpowiednia nazwa Header, powinno się nazywać MainPageStyled

2022-03-01 19:23 UTC, kostekd approved these changes

2022-03-01 19:23 UTC, kostekd commented on front/src/components/UI/Header/header.styled.ts
> +background-color: #282c34;
Brak wcięcia.

2022-03-01 20:14 UTC, DJ-Chemik requested changes

2022-03-01 20:14 UTC, DJ-Chemik commented on front/src/components/UI/Header/header.styled.ts
> +export const HeaderWrapper = styled.section`
Ogólnie ten komponent HeaderWrapper możesz bezpośrednio zaimportować w MainPage.tsx 
Oczywiście tylko najpierw należy zmienić nazwe zgodnie z komentarzem Dominika

2022-03-01 20:14 UTC, DJ-Chemik commented on front/src/components/UI/Header/header.tsx
> +import styled from "styled-components";
Taki import będziemy robić tylko w plikach .styled.ts

2022-03-01 20:14 UTC, DJ-Chemik commented on front/src/components/UI/Header/header.tsx
> +const Header = styled(HeaderWrapper)`
Ogólnie ten komponent i ogólnie plik nie są potrzebne. W poprzednim komentarzu napisałem że można zaimportować gdzieś bezpośrednio z pliku styled.ts. Style które są w 2 poniższych linijkach możesz dopisać bezpośrednio w tamtym komponencie - o ile są potrzebne. Inherit może być domyślnym zachowaniem więc jeśli nie powoduje dana reguła żadnych efektów to nie warto jej w ogóle pisać.

2022-03-01 20:14 UTC, DJ-Chemik commented on front/src/components/UI/Header/header.styled.ts
> +export const HeaderWrapper = styled.section`
niepotrzebny będzie wtedy również dodatkowy folder UI/Header ponieważ plik MainPage.styled.ts możesz umieścić bezpośrednio przy pliku MainPage.tsx

2022-03-02 18:22 UTC, DJ-Chemik approved these changes

2022-03-02 19:38 UTC, merged