[RDT-22] Delete endpoint
DJ-Chemik/Mercurius pull request #15
Opened 2022-03-16 18:25 UTC by kostekd

2022-03-17 15:37 UTC, DJ-Chemik requested changes

2022-03-17 15:37 UTC, DJ-Chemik commented on backend/src/app.module.ts
> +  controllers: [AppController, UserController],
ten kontroler nie jest powiązany (bezpośrednio) logicznie z AppModule. Zamiast tego tutaj powinien być importowany tylko moduł z userami

2022-03-17 15:37 UTC, DJ-Chemik commented on backend/src/app.module.ts
> +  providers: [AppService, UserService],
analogiczna sytuacja

2022-03-17 15:37 UTC, DJ-Chemik commented on backend/src/user/user.controller.ts
> +@Controller('user')
ogólna konwencja przewiduje raczej używanie liczby mnogiej w przypadku opisywania zasobów (czyli users zamiast user) chyba że w aplikacji byłby tylko jakiś 1 konkretny user to wtedy liczba pojedyncza by była adekwatna

2022-03-17 15:37 UTC, DJ-Chemik commented on backend/src/user/user.controller.ts
> +  remove(@Param('id') id: Number): string {
nazwa typu raczej powinna być z małej (prymityw a nie klasa). Chyba że Nest tego nie chce przepuścić, ale to daj znać

2022-04-04 18:01 UTC, Simon0030 approved these changes

2022-04-04 18:03 UTC, DJ-Chemik approved these changes

2022-05-11 20:03 UTC, merged