[RDT-21] Endpoint to create user
DJ-Chemik/Mercurius pull request #19
Opened 2022-03-21 12:05 UTC by tomaszStr1020

2022-03-21 16:37 UTC, DJ-Chemik requested changes

2022-03-21 16:37 UTC, DJ-Chemik commented on backend/src/user/user.controller.ts
> +        const data = {email: "email", login: "name"}
dane odnośnie usera mają być dostarczone poprzez API jako parametry.
Dodatkowo zwykle dla tego typu akcji stosuje się motodę POST, a nie GET

2022-03-21 16:37 UTC, DJ-Chemik commented on backend/src/user/user.controller.ts
> +        console.log("Dodany")
bez console.logów

2022-03-21 16:37 UTC, DJ-Chemik commented on backend/src/user/user.controller.ts
> +        return "Createuser"
taka zwrotka jest bardzo malo wartościowa - zamiast tego lepiej zwrócić np id utworzonego usera

2022-03-31 17:13 UTC, DJ-Chemik requested changes

2022-03-31 17:13 UTC, DJ-Chemik commented on backend/src/user/user.controller.ts
> +        const data = {email: email, login: name}
data to nieładna nazwa, nic nie mówi. Albo te parametry przekazać bezpośrednio i osobno do serwisu, albo niech cała metoda Post w ciele żądania zawiera stosowny obiekt (skłaniałbym się ku tej drugiej opcji)

2022-03-31 17:13 UTC, DJ-Chemik commented on backend/src/user/user.controller.ts
> +@Controller('createuser')
polecam poczytać o konwencji nzewnictwa w REST API - jeśli definiujemy jakąś podścieżke dla kontrolera to tak żeby wszystkie powiązane z nim endpointy logicznie rozwijały tą scieżke. Przy tym nazewnictwie ten kontroler można użyć tylko do tworzenia usera. Najlepszą nazwą tutaj byłoby po prostu "users"

2022-04-12 18:26 UTC, DJ-Chemik requested changes

2022-04-12 18:26 UTC, DJ-Chemik commented on backend/src/user/user.controller.ts
> +    @Post('create-user')
teraz endpoint wygląda tak: localhost:4000/users/create-user
Nie powiem jak powinno być ale podepnę przydatny materiał: https://nullpointerexception.pl/jak-tworzyc-rest-api/

2022-04-12 18:26 UTC, DJ-Chemik commented on backend/src/user/user.controller.ts
> +        return "Pomyślnie dodano użytkownika o adresie email: "+ newUserData.email + " oraz nazwie: "+newUserData.login
okej ale zamiast tego bardziej wskazane jest użycie template literals

2022-04-12 18:26 UTC, DJ-Chemik commented on backend/src/user/user.controller.ts
> +        return "Pomyślnie dodano użytkownika o adresie email: "+ newUserData.email + " oraz nazwie: "+newUserData.login
zwróć jednak uwagę że najpierw zostanie zwrócona wiadomość o pomyślnym dodaniu, a dopiero później zostanie to faktycznie dodane. Spróbuj wysłać nieprawidłowe dane dla serwisu, ale takie które są poprawne dla kontrolera

2022-04-17 16:36 UTC, DJ-Chemik approved these changes

2022-04-19 18:29 UTC, Simon0030 approved these changes

2022-04-20 08:31 UTC, merged