[RDT-24] Add Products and Auctions List
DJ-Chemik/Mercurius pull request #21
Opened 2022-03-24 19:47 UTC by Simon0030

2022-03-28 17:44 UTC, DJ-Chemik requested changes

2022-03-28 17:44 UTC, DJ-Chemik commented on front/src/components/App/SalesArea/SalesArea.tsx
> +  const [value, setValue] = useState("Products");
zamiast na sztywno wpisywać stringi w różnych miejscach w kodzie lepiej wykorzystać enuma

2022-03-28 17:44 UTC, DJ-Chemik commented on front/src/components/App/SalesArea/SalesArea.tsx
> +        <Products items={EXAMPLES_PRODUCTS} />
tak żeby bardziej zasymulować że te dane przyszły z backendu to oba EXAMPLES potraktuj jedynie jako wartości inicjalne. Do tych komponentów przekazuj już wartości trzymane np w useState

2022-03-28 17:44 UTC, DJ-Chemik commented on front/src/components/App/SalesArea/SalesArea.tsx
> +      {(value === "Products" || value === "Both") && (
zamiast takich "nieładnych" zapisów lepiej stworzyć zmienna typu shouldDisplayProducts albo coś w tym stylu

2022-03-28 17:44 UTC, DJ-Chemik commented on front/src/components/UI/AuctionView/AuctionBlock.tsx
> +export interface AuctionProps extends ProductProps {
mimo wszytsko lepiej bez dziedziczenia zapisać. Te elementy się raczej komponują niż dziedziczą po sobie. Bo co w sytuacji gdy produkt będzie miał jakiś parametr który dla aukcji jest bezużyteczny albo nawet nieprawidłowy? A jak są rozdzielone to nie zależą od siebie bezpośrednio

2022-03-28 17:44 UTC, DJ-Chemik commented on front/src/components/UI/AuctionView/AuctionBlock.tsx
> +  auction_site: string;
auctionSite, ale to też nie do końca prawidłowo bo sam string nie definiuje strony aukcyjnej. Co najwyzej może definiować jej nazwe albo id

2022-03-28 17:44 UTC, DJ-Chemik commented on front/src/components/UI/AuctionView/AuctionSector.tsx
> +  items: Array<AuctionProps>;
raczej tablice zapisujemy w taki sposób AuctionProps[], ale nie powinniśmy mieszać logiki obiektów czyli np takiego który definiuje aukcje z logiką interfejsów które tylko mówią jakie propsy ma otrzymać komponent

2022-03-28 17:44 UTC, DJ-Chemik commented on front/src/components/UI/ProductView/ProductFilter.tsx
> +  onChangeFilter: (arg0: string) => void;
arg0 słabo wygląda, podejrzewam że to po prostu jakieś value albo newValue

2022-03-28 17:44 UTC, DJ-Chemik commented on front/src/components/UI/ProductView/ProductFilter.tsx
> +interface HandlerProps {
niepotrzebnie, są już gotowe typy napisane i TS je dostarcza. To jakiś zwykły Event

2022-03-30 19:09 UTC, DJ-Chemik requested changes

2022-03-30 19:09 UTC, DJ-Chemik commented on front/src/components/App/SalesArea/SalesArea.tsx
> +  const shouldDisplayProducts = value === "Products" || value === "Both";
Wszystkie te stringi "Products", "Both" itd powinny zostać wyniesione do enuma. Dzięki temu bedziemy mogli zarządzać ich ilością i rodzajem z 1 miejsca. Pozwoli to uniknąć problemów w przyszłości gdy na przykład w innym pliku trzeba będzie użyć takiego samego rozróżnienia (później aktualizacja "gołych" stringów w kilku miejscach moze byc kłopotliwa dla programisty -  a gdy o jakimś zapomni to pojawi się bug w programie)

2022-03-30 19:09 UTC, DJ-Chemik commented on front/src/components/App/SalesArea/SalesArea.tsx
> +  name = "Products",
elementy w enumie raczej nazywa się WIELKIMI_LITERAMI. Z tym że ten enum to nie InitState tylko coś co opisze czym jest to value w dalszej części pliku.
```
enum AdekwatwaNazwa {
  PRODUCTS = "products",
  ...
}
```

2022-03-30 19:09 UTC, DJ-Chemik commented on front/src/components/UI/AuctionView/AuctionBlock.tsx
> +  img_src: string;
camelCase zamiast snake_case w nazewnictwie zmiennych i pól

2022-03-30 19:09 UTC, DJ-Chemik commented on front/src/components/UI/ProductView/ProductFilter.tsx
> +      <option value="Products">Products</option>
i tutaj jest dobry przykłąd że w innym miejscu pojawiły się znowu te wartości - za pół roku ktoś zapomni ich zmienić i będzie bug ;)

2022-03-30 19:59 UTC, DJ-Chemik approved these changes

2022-04-01 07:06 UTC, LenaPtak approved these changes

2022-04-01 09:32 UTC, merged