[RDT-26] Create sidebar with subpages
DJ-Chemik/Mercurius pull request #22
Opened 2022-03-25 00:35 UTC by olmichal

2022-03-25 12:21 UTC, Simon0030 commented on front/src/components/UI/Sidebar/Sidebar.tsx
> +    for(var i = 0; i < routes.length; i++){
Lepiej chyba let używać zamiast var

2022-03-28 17:57 UTC, DJ-Chemik requested changes

2022-03-28 17:57 UTC, DJ-Chemik commented on front/src/components/App/MaintenanceArea/MaintenanceArea.sidebarData.tsx
> +  {
Przydałby się interfejs opisujący elementy tej listy

2022-03-28 17:57 UTC, DJ-Chemik commented on front/src/components/App/MaintenanceArea/MaintenanceArea.tsx
> +    const routes = ['maintenance','products','orders','clients','returns','discounts']
i już powtarzają się w kilku miejscach te stringi. Przy późniejszej edycji albo dodaniu nowych funkcjonalności będą sprawiały dużo problemów. Zamiast tego lepiej wynieść je do enuma i wtedy będą zarządzane z 1 miejsca, co pozwoli uniknąć pomyłek w przyszłości

2022-03-28 17:57 UTC, DJ-Chemik commented on front/src/components/App/MaintenanceArea/MaintenanceArea.tsx
> +        const display = ['Witaj w panelu administracyjnym!','Produkty','Zamówienia','Klienci','Zwroty','Rabaty']
takie elementy powinny być zadeklarowane jako tablica constów albo enumów. Tutaj powinno być jedynie odowłanie do elementu

2022-03-28 17:57 UTC, DJ-Chemik commented on front/src/components/App/MaintenanceArea/MaintenanceArea.tsx
> +        for (var i = 0; i < routes.length; i++) {
do zmiany na routes.find

2022-03-28 17:57 UTC, DJ-Chemik commented on front/src/components/App/MaintenanceArea/MaintenanceArea.tsx
> +        var text = '';
nie używamy varów https://kursjs.pl/kurs/super-podstawy/zmienne#zasieg-zmiennych

2022-03-28 17:57 UTC, DJ-Chemik commented on front/src/components/App/MaintenanceArea/MaintenanceArea.tsx
> +        if(lastPath === routes[0]) {
odwoływanie po indeksie jest bardzo niewskazane. A co jeśli ktoś w przyszłości doda w środku nowy element? Zamiast tego enum lub tablica obiektów powinna rozwiązać sprawę

2022-03-28 17:57 UTC, DJ-Chemik commented on front/src/components/App/MaintenanceArea/MaintenanceArea.tsx
> +        if(lastPath === routes[1]) {
to wygląda jak dobry przypadek do uzycia switcha

2022-03-28 17:57 UTC, DJ-Chemik commented on front/src/components/App/MaintenanceArea/MaintenanceArea.tsx
> +            return (
powinniśmy rozdzielić logikę renderowania elementów od logiki zmiany tytułu

2022-03-28 17:57 UTC, DJ-Chemik commented on front/src/components/UI/Sidebar/Sidebar.tsx
> +  data: {
ten obiekt można wynieść do innego interfejsu i zastosować tutaj kompozycję

2022-03-31 18:17 UTC, DJ-Chemik requested changes

2022-03-31 18:17 UTC, DJ-Chemik commented on front/src/components/App/MaintenanceArea/MaintenanceArea.sidebarData.tsx
> +export enum routes {
nazwy enuma zaczynamy wielką literą

2022-03-31 18:17 UTC, DJ-Chemik commented on front/src/components/App/MaintenanceArea/MaintenanceArea.sidebarData.tsx
> +  home = "",
elementy enumów tylko z wielkich liter

2022-03-31 18:17 UTC, DJ-Chemik commented on front/src/components/App/MaintenanceArea/MaintenanceArea.sidebarData.tsx
> +export const SidebarData: MaintenanceAreaSidebarInterface[] = [
to jest nazwa zmiennej więc powinna zaczynać się małą literą a dalej  camelCase

2022-03-31 18:17 UTC, DJ-Chemik commented on front/src/components/UI/Sidebar/Sidebar.tsx
> +      "/",
tutaj mamy magiczne stringi - ktoś zmieni nazwe podstrony z maintenance na settings i sie posypie apka

2022-03-31 18:17 UTC, DJ-Chemik commented on front/src/components/UI/Sidebar/Sidebar.tsx
> +    let lastPath = window.location.pathname.split("/").pop();
to const

2022-03-31 18:17 UTC, DJ-Chemik commented on front/src/components/UI/Sidebar/Sidebar.tsx
> +    let newUrl =
to też

2022-03-31 18:17 UTC, DJ-Chemik commented on front/src/components/UI/Sidebar/Sidebar.tsx
> +            <SidebarListItem key={key} onClick={() => myRouter(val.link)}>
myRouter to rzeczownik a nazwy funkcji powinny być czasownikami bo opisuja jakąs akcje/czynność

2022-04-02 16:17 UTC, Simon0030 approved these changes

2022-04-04 17:02 UTC, DJ-Chemik approved these changes

2022-04-04 17:02 UTC, DJ-Chemik commented on front/src/components/App/MaintenanceArea/MaintenanceArea.tsx
> +  const myDiv = changeDiv();
myDiv to słaba nazwa, patrząc na nią nie mam pojecia co oznacza

2022-04-04 17:02 UTC, DJ-Chemik commented on front/src/components/UI/Sidebar/Sidebar.tsx
> +        {props.data.map((val, key) => {
to ogólnie jest ok, ale proponowałbym wynieść do jakiejś funkcji renderCośTam.

2022-04-04 17:53 UTC, merged