[RDT-1] Change SalesArea background
DJ-Chemik/Mercurius pull request #3
Opened 2022-03-02 09:44 UTC by olmichal

2022-03-02 18:13 UTC, DJ-Chemik requested changes

2022-03-02 18:13 UTC, DJ-Chemik commented on front/package.json
> +    "@types/react-router-dom": "^5.1.7",
niepotrzebna zmiana, zależności powinny być listowane alfabetycznie

2022-03-02 18:13 UTC, DJ-Chemik commented on front/src/components/App/SalesArea/SalesArea.tsx
> +import styled from "styled-components";
Styled componenty proszę wynieś do osobnego pliku

2022-03-02 20:28 UTC, DJ-Chemik approved these changes

2022-03-03 13:08 UTC, kostekd approved these changes

2022-03-04 21:09 UTC, merged