[RDT-2] Added main page routing
DJ-Chemik/Mercurius pull request #4
Opened 2022-03-02 18:35 UTC by tomaszStr1020

Now main page sections names redirects by click on

2022-03-02 20:07 UTC, kostekd approved these changes
Jak dla mnie jest dobrze.

2022-03-02 20:23 UTC, DJ-Chemik requested changes

2022-03-02 20:23 UTC, DJ-Chemik commented on front/src/components/App/MainPage/MainPage.tsx
> +        <RouteLink to={APP_PAGE.MAINTENANCE}>
Czy te strony się obecnie otwierają? Nikt ich nie implementował więc trzeba jeszcze dorobić każdą z tych stronek na podobnej zasadzie jak zrobione jest SalesArea. Tak żeby powrót na stronę główną działał prawidłowo.

2022-03-07 15:51 UTC, DJ-Chemik requested changes

2022-03-07 15:51 UTC, DJ-Chemik commented on front/src/components/App/Maintenance/Maintenance.tsx
> +const Maintenance = () => {
Jeszcze bym prosił żeby te komponenty nazwać według tej konwencji co SalesArea. Czyli w tym wypadku MaintenanceArea. To samo tyczy się pliku. Tak w celu zachowania spójności

2022-03-07 15:51 UTC, DJ-Chemik commented on front/src/components/App/Help/Help.tsx
> +            Help :(
:(

2022-03-09 19:16 UTC, DJ-Chemik commented on front/src/components/App/MaintenanceArea/MaintenancePage.tsx
> +const MaintenancePage = () => {
Trochę nam się rozjechało. W założeniu chciałem żeby było MainPage i jakieś Area (SalesArea, MaintenanceArea itd). Ale widzę że to rzeczywiscie jest mylące. Więc jeszcze bym prosił żebyś wszędzie podmienił albo na Page albo na Area - niech wszędzie będzie identycznie (to które wybierzesz już zależy od Ciebie)

2022-03-13 11:05 UTC, DJ-Chemik approved these changes

2022-03-15 20:21 UTC, merged