[RDT-5] Add Title component
DJ-Chemik/Mercurius pull request #6
Opened 2022-03-08 23:30 UTC by LenaPtak

Mam nadzieję, że o to chodziło z title.styled.ts. :)

2022-03-08 23:42 UTC, tomaszStr1020 commented on front/src/components/UI/Button/Button.styled.ts
> +  /*width: 25%;*/
Chyba zapomnienie o odkomentowaniu

2022-03-08 23:42 UTC, tomaszStr1020 approved these changes
Wg mnie wygląda dobrze

2022-03-09 19:25 UTC, DJ-Chemik requested changes

2022-03-09 19:25 UTC, DJ-Chemik commented on front/src/components/App/MainPage/MainPage.tsx
> +import Title from "../../UI/Title/Title";
chyba nieużywany import

2022-03-09 19:25 UTC, DJ-Chemik commented on front/src/components/App/App.css
> +.App-title {
niepotrzebny juz kod ;)

2022-03-09 19:25 UTC, DJ-Chemik commented on front/src/components/UI/Title/Title.tsx
> +
raczej zostawmy jeden enter, nie potrzeba zbędnie wydłużać kodu

2022-03-09 19:25 UTC, DJ-Chemik commented on front/src/components/UI/Title/Title.styled.ts
> +export const TitleLook = styled.div`
raczej widziałbym tutaj nazwę TitleStyledWrapper, chociaż ta twoja troszke mnie zaskoczyła (pozytywnie)

2022-03-10 13:02 UTC, DJ-Chemik requested changes

2022-03-10 13:02 UTC, DJ-Chemik commented on front/src/components/UI/Title/Title.tsx
> +
podbijam

2022-03-10 13:02 UTC, DJ-Chemik commented on front/src/components/UI/Title/Title.styled.ts
> +export const TitleLook = styled.div`
podbijam

2022-03-10 15:28 UTC, kostekd approved these changes
Po poprawce uwag od kolegów, wydaję mi się, że jest okej.

2022-03-11 12:30 UTC, DJ-Chemik approved these changes

2022-03-11 12:36 UTC, merged