Feature/rdt 10
DJ-Chemik/Mercurius pull request #8
Opened 2022-03-09 19:52 UTC by Simon0030

2022-03-10 13:33 UTC, DJ-Chemik requested changes

2022-03-10 13:33 UTC, DJ-Chemik commented on front/package.json
> +    "react-rounded-image": "^2.0.14",
jeśli jest nieużywany, to wyrzucić go. Niech niepotrzebnie się nie dociągają dodatkowe kilobajty.

2022-03-10 13:33 UTC, DJ-Chemik commented on front/src/components/App/SalesArea/SalesArea.tsx
> +  const examples = [
jeśli definujemy taką stała to nie umieszczamy jej w komponencie, ponieważ nie chcemy żeby przy każdym przerenderowaniu komponentu na nowo musiała się tworzyć cała lista. Zamiast tego możesz to wynieść po prostu ponad definicję SalesArea.

Druga uwaga to nazewnictwo. Samo examples nie jest złe, ale nie mówi od razu co tam się znajduje. Zamiast tego można to nazwać np. EXAMPLE_COMPANIES (wielkimi literami żeby zaznaczyć, że nigdzie nie powinno to być modyfikowane).

2022-03-10 13:33 UTC, DJ-Chemik commented on front/src/components/UI/CompanyView/CompaniesSector.tsx
> +const Companies = (props: any) => {
zamiast any zdefiniuj proszę interfejs (tak jak jest to zrobione  np w Button.tsx). Gdy dajemy any, to niestety kompilator przestaje sprawdzać czy na pewno odwołujemy się do prawidłowych danych. Szczególnie problematyczne może się to okazać w przyszłości, szczególnie jeśli ktoś inny będzie próbował analizować kod

2022-03-10 13:33 UTC, DJ-Chemik commented on front/src/components/UI/CompanyView/CompaniesSector.tsx
> +    <div>
przy takim rozwiązaniu jeśli pojawi się w tablicy z przykładami kolejny item to niestety nie zostanie wyświetlony...

Zamiast tego powinieneś uzyc tutaj podejścia z wykorzystaniem funkcji .map wywoływanej na tablicy. Wtedy dynamicznie będą tworzyć się kolejne elementy jeśli zmienimy coś w liście

2022-03-13 19:46 UTC, DJ-Chemik requested changes

2022-03-13 19:46 UTC, DJ-Chemik commented on front/src/components/UI/CompanyView/CompaniesSector.tsx
> +        (company: { title: string; img_src: string; id: string }) => (
Tutaj tylko wynieś ten typ { title: string; img_src: string; id: string } jako interfejs. Nad interfejsem Propsów możesz po prostu zadeklarować

2022-03-13 19:46 UTC, DJ-Chemik commented on front/src/components/UI/CompanyView/CompaniesSector.tsx
> +          <CompanyBlock
Tutaj jest bardzo istotny błąd o którym React informuje dopiero w konsoli (jak otworzysz to zobaczysz error typu: "Each child should have unique key").
Rozwiązanie jest proste: przekazać jako props parametr key={tutaj jakaś unikalna wartość dla każdego elementu z listy}

Często pytanie o to dlaczego klucze są potrzebne pojawia się na różnych rozmowach kwalifikacyjnych itd więc warto wiedzieć nie tylko jak naprawić ten błąd ale też dlaczego trzeba to zrobić i w jaki sposób to pomaga (w tym kursie od Maxa na Udemy jest to wyjaśnione)

2022-03-14 18:22 UTC, DJ-Chemik commented on front/src/components/UI/CompanyView/CompaniesSector.tsx
> +          key={company.key}
można było po prostu zrobić key={company.id}

2022-03-14 19:03 UTC, DJ-Chemik approved these changes

2022-03-15 08:48 UTC, LenaPtak reviewed
Wszystko ok

2022-03-15 08:49 UTC, LenaPtak approved these changes

2022-03-15 11:03 UTC, merged