[RDT-12] Add Product Panel
DJ-Chemik/Mercurius pull request #9
Opened 2022-03-10 12:54 UTC by LenaPtak

2022-03-10 13:44 UTC, DJ-Chemik requested changes

2022-03-10 13:44 UTC, DJ-Chemik commented on front/src/components/App/ProductArea/ProductArea.tsx
> +
w JSXie nie powinno się robić nawet pojedynczych enterów

2022-03-10 13:44 UTC, DJ-Chemik commented on front/src/components/App/ProductArea/ProductArea.tsx
> +        <FieldsetStyledWrapper>
Bardzo długi wyszedł ten JSX ;) Myślę że dobrym rozwiązaniem byłoby utworzyć komponenty które odpowiadałyby za pewną grupę powiązanych danych. Dodatkowo pytanie czy na pewno każde pole będzie potrzebowało całej szerokości ekranu? Może lepiej jeśli niektóre pola zajmą mniej miejsca (np ceny) i wtedy poprawi się przejrzystość.

2022-03-10 13:44 UTC, DJ-Chemik commented on front/src/components/App/ProductArea/ProductArea.styled.ts
> +export const InputStyle = styled.div`
jeśli chodzi o tą nazwę to bardziej pasuje StyledInput

2022-03-13 18:43 UTC, DJ-Chemik requested changes

2022-03-13 18:43 UTC, DJ-Chemik commented on front/src/components/App/ProductArea/ProductArea.styled.ts
> +export const Row1 = styled.div`
Dlaczego Row1? Co ta jedynka tutaj oznacza? Nigdzie nie widzę Row2, Row3 więc nawet ciężko mi zgadnąć dlaczego ten je ponumerowany. Może chodziło o coś w stylu FirstRow? TopLevelRow? MainRow?

2022-03-13 18:43 UTC, DJ-Chemik commented on front/src/components/UI/ProductPrices/ProductPrices.tsx
> +      <Col1>
Tutaj dobrze widać że można to rozbić na 2 komponenty. Są nawet zgrupowane w Col1 i Col2 (+te nazwy również wymagają poprawy, gdy w nazwie komponentu pojawia się cyfra, to znaczy że coś semantycznie jest nie tak).

2022-03-14 18:36 UTC, DJ-Chemik approved these changes

2022-03-14 19:19 UTC, Simon0030 approved these changes

2022-03-14 19:20 UTC, merged